//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibintek
{
    using System;
    using System.Collections.Generic;
    
    public partial class AZI
    {
        public AZI()
        {
            this.Classifier = new HashSet<Classifier>();
        }
    
        public int AZIID { get; set; }
        public string AZI1 { get; set; }
        public int AZIPoint { get; set; }
    
        public virtual ICollection<Classifier> Classifier { get; set; }
    }
}
