//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibintek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classifier
    {
        public int ClassifierID { get; set; }
        public int ClassifierCostType { get; set; }
        public int ClassifierTypeByContent { get; set; }
        public int ClassifierCoveredProjectType { get; set; }
        public int ClassifierBelongingToSystem { get; set; }
        public int ClassifierPrivacyLevel { get; set; }
        public int ClassifierInternetAccess { get; set; }
        public int ClassifierEconomicEffect { get; set; }
        public int ClassifierArchitecturalDesign { get; set; }
        public int ClassifierAZI { get; set; }
        public int ClassifierEquipment { get; set; }
        public int ClassifierSoftwareLicenses { get; set; }
        public int ClassifierBusinessUnitSupport { get; set; }
        public int ClassifierSum { get; set; }
        public int ClassifierCriticalyLevel { get; set; }
        public int ClassifierDecisionMakingLevel { get; set; }
        public int ClassifierICLevel { get; set; }
        public int ClassifierQuantityCC { get; set; }
        public int ClassifierQuantityIS { get; set; }
        public int ClassifierNumberOfStakeholders { get; set; }
        public int ClassifierQuantityContract { get; set; }
        public int ClassifierBranch { get; set; }
        public int ClassifierQuantityContractor { get; set; }
        public int ClassifierEmployeeManager { get; set; }
        public Nullable<int> ClassifierEmployeeAdmin { get; set; }
        public int ClassifierProjectType { get; set; }
    
        public virtual ArchitecturalDesign ArchitecturalDesign { get; set; }
        public virtual AZI AZI { get; set; }
        public virtual BelongingToSystem BelongingToSystem { get; set; }
        public virtual BusinessUnitSupport BusinessUnitSupport { get; set; }
        public virtual CostType CostType { get; set; }
        public virtual CoveredByTheProjectType CoveredByTheProjectType { get; set; }
        public virtual CriticalityLevel CriticalityLevel { get; set; }
        public virtual DecisionMakingLevel DecisionMakingLevel { get; set; }
        public virtual EconomicEffect EconomicEffect { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ICLevel ICLevel { get; set; }
        public virtual InternetAccess InternetAccess { get; set; }
        public virtual PrivacyLevel PrivacyLevel { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual PurchaseOfEquipment PurchaseOfEquipment { get; set; }
        public virtual PurchasingSoftwareLicenses PurchasingSoftwareLicenses { get; set; }
        public virtual Sum Sum { get; set; }
        public virtual TypeByContent TypeByContent { get; set; }
    }
}
