//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibintek
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFTE
    {
        public EmployeeFTE()
        {
            this.Employee = new HashSet<Employee>();
            this.ProjectType = new HashSet<ProjectType>();
            this.ProjectType1 = new HashSet<ProjectType>();
        }
    
        public int EmployeeFTEID { get; set; }
        public string EmployeeFTE1 { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<ProjectType> ProjectType { get; set; }
        public virtual ICollection<ProjectType> ProjectType1 { get; set; }
    }
}
