//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibintek
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Classifier = new HashSet<Classifier>();
            this.Classifier1 = new HashSet<Classifier>();
        }
    
        public int EmployeeID { get; set; }
        public string EmployeeFullName { get; set; }
        public Nullable<int> EmployeeType { get; set; }
        public int EmployeeFTE { get; set; }
    
        public virtual ICollection<Classifier> Classifier { get; set; }
        public virtual ICollection<Classifier> Classifier1 { get; set; }
        public virtual EmployeeFTE EmployeeFTE1 { get; set; }
        public virtual EmployeeType EmployeeType1 { get; set; }
    }
}
