//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibintek
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeType
    {
        public EmployeeType()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public int EmployeeTypeID { get; set; }
        public string EmployeeType1 { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
