//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sibintek
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectType
    {
        public ProjectType()
        {
            this.Classifier = new HashSet<Classifier>();
        }
    
        public int ProjectTypeID { get; set; }
        public string ProjectType1 { get; set; }
        public int ProjectTypeManagerFTE { get; set; }
        public Nullable<int> ProjectTypeAdminFTE { get; set; }
    
        public virtual EmployeeFTE EmployeeFTE { get; set; }
        public virtual EmployeeFTE EmployeeFTE1 { get; set; }
        public virtual ICollection<Classifier> Classifier { get; set; }
    }
}
